/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
import Master.*;
import Transaksi.*;
import Koneksi.Koneksi;
import Koneksi.Session;
import java.awt.Color;
import Login.*;
/**
 *
 * @author Lenovo
 */
public class Dashboard_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */

    
    boolean[] stat = new boolean[10];

    Dokter dokter1 = new Dokter();
    Kamar kamar1 = new Kamar();
    Pasien pasien1 = new Pasien();
    Obat obat1 = new Obat();
    Petugas petugas1 = new Petugas();
    User user1 = new User();
    Tindakan tindakan1 = new Tindakan();
    RawatInap inap1 = new RawatInap();
    RawatJalan jalan1 = new RawatJalan();
    Riwayat riwayat1 = new Riwayat();
    public Dashboard_Admin() {
        initComponents();
        addToPane();
        String akses1 = Session.getAkses();
        akses.setText(akses1);
        String nama1 = Session.getId();
        nama.setText(nama1);

        
    }
    private void resetstat() {
        for (int i = 0; i < 10; i++) {
            stat[i] = false;
        }
    }
    private void addToPane() {
        jDesktopPane1.add(dokter1);
        jDesktopPane1.add(kamar1);
        jDesktopPane1.add(pasien1);
        jDesktopPane1.add(obat1);
        jDesktopPane1.add(petugas1);
        jDesktopPane1.add(user1);
        jDesktopPane1.add(tindakan1);
        jDesktopPane1.add(inap1);
        jDesktopPane1.add(jalan1);
        jDesktopPane1.add(riwayat1);
    }
    private void hide_pane() {
        if (stat[0] == true) {
            dokter1.dispose();
        }
        if (stat[1] == true) {
            kamar1.dispose();
        }
        if (stat[2] == true) {
            pasien1.dispose();
        }
        if (stat[3] == true) {
            obat1.dispose();
        }
        if (stat[4] == true) {
            petugas1.dispose();
        }
        if (stat[5] = true) {
            user1.dispose();
        }
        if (stat[6] == true) {
            tindakan1.dispose();
        }
        if (stat[7] == true) {
            inap1.dispose();
        }
        if (stat[8] == true) {
            jalan1.dispose();
        }
        if (stat[9] == true) {
            riwayat1.dispose();
        }
        resetstat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_menu = new rsbuttom.RSButtonMetro();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        akses = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn8 = new rsbuttom.RSButtonMetro();
        btn1 = new rsbuttom.RSButtonMetro();
        btn11 = new rsbuttom.RSButtonMetro();
        jLabel3 = new javax.swing.JLabel();
        btn10 = new rsbuttom.RSButtonMetro();
        btn9 = new rsbuttom.RSButtonMetro();
        btn7 = new rsbuttom.RSButtonMetro();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(1, 152, 117));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 60));
        jPanel2.setLayout(null);

        btn_menu.setBackground(new java.awt.Color(1, 152, 117));
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btn_menu.setColorHover(new java.awt.Color(1, 152, 117));
        btn_menu.setColorNormal(new java.awt.Color(1, 152, 117));
        btn_menu.setColorPressed(new java.awt.Color(1, 152, 117));
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn_menu);
        btn_menu.setBounds(19, 11, 59, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(1350, 0, 20, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(1330, -10, 30, 40);

        akses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akses.setForeground(new java.awt.Color(255, 255, 255));
        akses.setText("jLabel6");
        jPanel2.add(akses);
        akses.setBounds(1130, 30, 120, 17);

        nama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("jLabel6");
        jPanel2.add(nama);
        nama.setBounds(1130, 10, 120, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Nama");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(1040, 10, 60, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Akses");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(1040, 30, 40, 17);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1366, 60);

        pnlMenu.setBackground(new java.awt.Color(214, 217, 223));

        jPanel4.setBackground(new java.awt.Color(214, 217, 223));

        btn8.setBackground(new java.awt.Color(214, 217, 223));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kamar.png"))); // NOI18N
        btn8.setText("KAMAR");
        btn8.setColorHover(new java.awt.Color(166, 166, 166));
        btn8.setColorNormal(new java.awt.Color(214, 217, 223));
        btn8.setColorPressed(new java.awt.Color(166, 166, 166));
        btn8.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn8.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn8.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn8.setIconTextGap(25);
        btn8.setMaximumSize(new java.awt.Dimension(121, 41));
        btn8.setMinimumSize(new java.awt.Dimension(121, 41));
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn8MousePressed(evt);
            }
        });
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(214, 217, 223));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tindakan.png"))); // NOI18N
        btn1.setText("TINDAKAN");
        btn1.setColorHover(new java.awt.Color(166, 166, 166));
        btn1.setColorNormal(new java.awt.Color(214, 217, 223));
        btn1.setColorPressed(new java.awt.Color(166, 166, 166));
        btn1.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn1.setIconTextGap(25);
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn1MousePressed(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn11.setBackground(new java.awt.Color(214, 217, 223));
        btn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btn11.setText("USER");
        btn11.setColorHover(new java.awt.Color(166, 166, 166));
        btn11.setColorNormal(new java.awt.Color(214, 217, 223));
        btn11.setColorPressed(new java.awt.Color(166, 166, 166));
        btn11.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn11.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn11.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn11.setIconTextGap(25);
        btn11.setMaximumSize(new java.awt.Dimension(121, 41));
        btn11.setMinimumSize(new java.awt.Dimension(121, 41));
        btn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn11MousePressed(evt);
            }
        });
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Master");

        btn10.setBackground(new java.awt.Color(214, 217, 223));
        btn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/petugas.png"))); // NOI18N
        btn10.setText("PETUGAS");
        btn10.setColorHover(new java.awt.Color(166, 166, 166));
        btn10.setColorNormal(new java.awt.Color(214, 217, 223));
        btn10.setColorPressed(new java.awt.Color(166, 166, 166));
        btn10.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn10.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn10.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn10.setIconTextGap(25);
        btn10.setMaximumSize(new java.awt.Dimension(121, 41));
        btn10.setMinimumSize(new java.awt.Dimension(121, 41));
        btn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn10MousePressed(evt);
            }
        });
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(214, 217, 223));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/obat.png"))); // NOI18N
        btn9.setText("OBAT");
        btn9.setColorHover(new java.awt.Color(166, 166, 166));
        btn9.setColorNormal(new java.awt.Color(214, 217, 223));
        btn9.setColorPressed(new java.awt.Color(166, 166, 166));
        btn9.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn9.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn9.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn9.setIconTextGap(25);
        btn9.setMaximumSize(new java.awt.Dimension(121, 41));
        btn9.setMinimumSize(new java.awt.Dimension(121, 41));
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn9MousePressed(evt);
            }
        });
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(214, 217, 223));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dokter.png"))); // NOI18N
        btn7.setText("DOKTER");
        btn7.setColorHover(new java.awt.Color(166, 166, 166));
        btn7.setColorNormal(new java.awt.Color(214, 217, 223));
        btn7.setColorPressed(new java.awt.Color(166, 166, 166));
        btn7.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn7.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn7.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn7.setIconTextGap(25);
        btn7.setMaximumSize(new java.awt.Dimension(121, 41));
        btn7.setMinimumSize(new java.awt.Dimension(121, 41));
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn7MousePressed(evt);
            }
        });
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn11, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(btn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlMenu);
        pnlMenu.setBounds(0, 60, 180, 710);

        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("BigNoodleTitling", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SELAMAT DATANG DI SISTEM INFORMASI");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(336, 74, 525, 54);

        jLabel9.setFont(new java.awt.Font("BigNoodleTitling", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KLINIK KESEHATAN HUSADA MULIA");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(408, 134, 342, 41);

        jLabel10.setFont(new java.awt.Font("BigNoodleTitling", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("JL. RAYA WONOREJO NO. 167, LUMAJANG");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(443, 186, 266, 27);

        jLabel11.setFont(new java.awt.Font("BigNoodleTitling", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/hospital_icon-icons.com_76234.png"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(450, 300, 256, 290);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/free-dark-green-wallpaper-41165-42149-hd-wallpapers.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 670);

        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(200, 80, 1150, 670);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        
        System.exit(0);
        
    }//GEN-LAST:event_jLabel2MousePressed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        hide_pane();
        stat[6] = true;
        
        tindakan1  = new Tindakan();
        jDesktopPane1.add(tindakan1);
        tindakan1.setVisible(true);
        if(this.btn1.isSelected()){
            this.btn1.setColorNormal(new Color(166,166,166));
            this.btn1.setColorHover(new Color(166,166,166));
            this.btn1.setColorPressed(new Color(166,166,166));
            
            this.btn7.setColorNormal(new Color(214,217,223));
            this.btn7.setColorHover(new Color(166,166,166));
            this.btn7.setColorPressed(new Color(214,217,223));
            
            this.btn8.setColorNormal(new Color(214,217,223));
            this.btn8.setColorHover(new Color(166,166,166));
            this.btn8.setColorPressed(new Color(214,217,223));
            
            this.btn9.setColorNormal(new Color(214,217,223));
            this.btn9.setColorHover(new Color(166,166,166));
            this.btn9.setColorPressed(new Color(214,217,223));
            
            this.btn10.setColorNormal(new Color(214,217,223));
            this.btn10.setColorHover(new Color(166,166,166));
            this.btn10.setColorPressed(new Color(214,217,223));
            
            this.btn11.setColorNormal(new Color(214,217,223));
            this.btn11.setColorHover(new Color(166,166,166));
            this.btn11.setColorPressed(new Color(214,217,223));
        }
        else {
            this.btn1.setColorNormal(new Color(214,217,223));
            this.btn1.setColorHover(new Color(166,166,166));
            this.btn1.setColorPressed(new Color(214,217,223));       
        }
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        int posisi = this.pnlMenu.getX();
        if (posisi > -1){
           Animacion.Animacion.mover_izquierda(0, -188, 3, 2, pnlMenu);
        } else {
           Animacion.Animacion.mover_derecha(-188, 0, 3, 2, pnlMenu);
        }
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        hide_pane();
        stat[1] = true;
        
        kamar1  = new Kamar();
        jDesktopPane1.add(kamar1);
        kamar1.setVisible(true);
        if(this.btn8.isSelected()){
            this.btn1.setColorNormal(new Color(214,217,223));
            this.btn1.setColorHover(new Color(166,166,166));
            this.btn1.setColorPressed(new Color(214,217,223));

            this.btn7.setColorNormal(new Color(214,217,223));
            this.btn7.setColorHover(new Color(166,166,166));
            this.btn7.setColorPressed(new Color(214,217,223));
            
            this.btn8.setColorNormal(new Color(166,166,166));
            this.btn8.setColorHover(new Color(166,166,166));
            this.btn8.setColorPressed(new Color(166,166,166));

            this.btn9.setColorNormal(new Color(214,217,223));
            this.btn9.setColorHover(new Color(166,166,166));
            this.btn9.setColorPressed(new Color(214,217,223));

            this.btn10.setColorNormal(new Color(214,217,223));
            this.btn10.setColorHover(new Color(166,166,166));
            this.btn10.setColorPressed(new Color(214,217,223));

            this.btn11.setColorNormal(new Color(214,217,223));
            this.btn11.setColorHover(new Color(166,166,166));
            this.btn11.setColorPressed(new Color(214,217,223));
        }
        else {
            this.btn8.setColorNormal(new Color(214,217,223));
            this.btn8.setColorHover(new Color(166,166,166));
            this.btn8.setColorPressed(new Color(214,217,223));
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        hide_pane();
        stat[3] = true;
        
        obat1  = new Obat();
        jDesktopPane1.add(obat1);
        obat1.setVisible(true);
        if(this.btn9.isSelected()){
            this.btn1.setColorNormal(new Color(214,217,223));
            this.btn1.setColorHover(new Color(166,166,166));
            this.btn1.setColorPressed(new Color(214,217,223));
            
            this.btn7.setColorNormal(new Color(214,217,223));
            this.btn7.setColorHover(new Color(166,166,166));
            this.btn7.setColorPressed(new Color(214,217,223));
            
            this.btn8.setColorNormal(new Color(214,217,223));
            this.btn8.setColorHover(new Color(166,166,166));
            this.btn8.setColorPressed(new Color(214,217,223));
            
            this.btn9.setColorNormal(new Color(166,166,166));
            this.btn9.setColorHover(new Color(166,166,166));
            this.btn9.setColorPressed(new Color(166,166,166));

            this.btn10.setColorNormal(new Color(214,217,223));
            this.btn10.setColorHover(new Color(166,166,166));
            this.btn10.setColorPressed(new Color(214,217,223));

            this.btn11.setColorNormal(new Color(214,217,223));
            this.btn11.setColorHover(new Color(166,166,166));
            this.btn11.setColorPressed(new Color(214,217,223));
        }
        else {
            this.btn9.setColorNormal(new Color(214,217,223));
            this.btn9.setColorHover(new Color(166,166,166));
            this.btn9.setColorPressed(new Color(214,217,223));
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        hide_pane();
        stat[4] = true;
        
        petugas1  = new Petugas();
        jDesktopPane1.add(petugas1);
        petugas1.setVisible(true);
        if(this.btn10.isSelected()){
            this.btn1.setColorNormal(new Color(214,217,223));
            this.btn1.setColorHover(new Color(166,166,166));
            this.btn1.setColorPressed(new Color(214,217,223));
            this.btn7.setColorNormal(new Color(214,217,223));
            this.btn7.setColorHover(new Color(166,166,166));
            this.btn7.setColorPressed(new Color(214,217,223));
            
            this.btn8.setColorNormal(new Color(214,217,223));
            this.btn8.setColorHover(new Color(166,166,166));
            this.btn8.setColorPressed(new Color(214,217,223));
            
            this.btn9.setColorNormal(new Color(214,217,223));
            this.btn9.setColorHover(new Color(166,166,166));
            this.btn9.setColorPressed(new Color(214,217,223));
            
            this.btn10.setColorNormal(new Color(166,166,166));
            this.btn10.setColorHover(new Color(166,166,166));
            this.btn10.setColorPressed(new Color(166,166,166));

            this.btn11.setColorNormal(new Color(214,217,223));
            this.btn11.setColorHover(new Color(166,166,166));
            this.btn11.setColorPressed(new Color(214,217,223));
        }
        else {
            this.btn10.setColorNormal(new Color(214,217,223));
            this.btn10.setColorHover(new Color(166,166,166));
            this.btn10.setColorPressed(new Color(214,217,223));
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        hide_pane();
        stat[5] = true;
        
        user1  = new User();
        jDesktopPane1.add(user1);
        user1.setVisible(true);
        if(this.btn11.isSelected()){
            this.btn1.setColorNormal(new Color(214,217,223));
            this.btn1.setColorHover(new Color(166,166,166));
            this.btn1.setColorPressed(new Color(214,217,223));
            
            this.btn7.setColorNormal(new Color(214,217,223));
            this.btn7.setColorHover(new Color(166,166,166));
            this.btn7.setColorPressed(new Color(214,217,223));
            
            this.btn8.setColorNormal(new Color(214,217,223));
            this.btn8.setColorHover(new Color(166,166,166));
            this.btn8.setColorPressed(new Color(214,217,223));
            
            this.btn9.setColorNormal(new Color(214,217,223));
            this.btn9.setColorHover(new Color(166,166,166));
            this.btn9.setColorPressed(new Color(214,217,223));
            
            this.btn10.setColorNormal(new Color(214,217,223));
            this.btn10.setColorHover(new Color(166,166,166));
            this.btn10.setColorPressed(new Color(214,217,223));
            
            this.btn11.setColorNormal(new Color(166,166,166));
            this.btn11.setColorHover(new Color(166,166,166));
            this.btn11.setColorPressed(new Color(166,166,166));

        }
        else {
            this.btn11.setColorNormal(new Color(214,217,223));
            this.btn11.setColorHover(new Color(166,166,166));
            this.btn11.setColorPressed(new Color(214,217,223));
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MousePressed
        // TODO add your handling code here:
        this.btn1.setSelected(true);
        this.btn7.setSelected(false);
        this.btn8.setSelected(false);
        this.btn9.setSelected(false);
        this.btn10.setSelected(false);
        this.btn11.setSelected(false); 
        
        
    }//GEN-LAST:event_btn1MousePressed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        hide_pane();
        stat[0] = true;
        dokter1.setVisible(true);
        
        dokter1  = new Dokter();
        jDesktopPane1.add(dokter1);
        dokter1.setVisible(true);
        if(this.btn7.isSelected()){
            this.btn1.setColorNormal(new Color(214,217,223));
            this.btn1.setColorHover(new Color(166,166,166));
            this.btn1.setColorPressed(new Color(214,217,223));

            this.btn7.setColorNormal(new Color(166,166,166));
            this.btn7.setColorHover(new Color(166,166,166));
            this.btn7.setColorPressed(new Color(166,166,166));

            this.btn8.setColorNormal(new Color(214,217,223));
            this.btn8.setColorHover(new Color(166,166,166));
            this.btn8.setColorPressed(new Color(214,217,223));

            this.btn9.setColorNormal(new Color(214,217,223));
            this.btn9.setColorHover(new Color(166,166,166));
            this.btn9.setColorPressed(new Color(214,217,223));

            this.btn10.setColorNormal(new Color(214,217,223));
            this.btn10.setColorHover(new Color(166,166,166));
            this.btn10.setColorPressed(new Color(214,217,223));

            this.btn11.setColorNormal(new Color(214,217,223));
            this.btn11.setColorHover(new Color(166,166,166));
            this.btn11.setColorPressed(new Color(214,217,223));
        }
        else {
            this.btn7.setColorNormal(new Color(214,217,223));
            this.btn7.setColorHover(new Color(166,166,166));
            this.btn7.setColorPressed(new Color(214,217,223));
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MousePressed
        // TODO add your handling code here:
        this.btn1.setSelected(false);
        this.btn7.setSelected(true);
        this.btn8.setSelected(false);
        this.btn9.setSelected(false);
        this.btn10.setSelected(false);
        this.btn11.setSelected(false);
    }//GEN-LAST:event_btn7MousePressed

    private void btn8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MousePressed
        // TODO add your handling code here:
        this.btn1.setSelected(false);
        this.btn7.setSelected(false);
        this.btn8.setSelected(true);
        this.btn9.setSelected(false);
        this.btn10.setSelected(false);
        this.btn11.setSelected(false);
    }//GEN-LAST:event_btn8MousePressed

    private void btn9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MousePressed
        // TODO add your handling code here:
        this.btn1.setSelected(false);
        this.btn7.setSelected(false);
        this.btn8.setSelected(false);
        this.btn9.setSelected(true);
        this.btn10.setSelected(false);
        this.btn11.setSelected(false);
    }//GEN-LAST:event_btn9MousePressed

    private void btn10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MousePressed
        // TODO add your handling code here:
        this.btn1.setSelected(false);
        this.btn7.setSelected(false);
        this.btn8.setSelected(false);
        this.btn9.setSelected(false);
        this.btn10.setSelected(true);
        this.btn11.setSelected(false);
    }//GEN-LAST:event_btn10MousePressed

    private void btn11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn11MousePressed
        // TODO add your handling code here:
        this.btn1.setSelected(false);
        this.btn7.setSelected(false);
        this.btn8.setSelected(false);
        this.btn9.setSelected(false);
        this.btn10.setSelected(false);
        this.btn11.setSelected(true);
    }//GEN-LAST:event_btn11MousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame. ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akses;
    private rsbuttom.RSButtonMetro btn1;
    private rsbuttom.RSButtonMetro btn10;
    private rsbuttom.RSButtonMetro btn11;
    private rsbuttom.RSButtonMetro btn7;
    private rsbuttom.RSButtonMetro btn8;
    private rsbuttom.RSButtonMetro btn9;
    private rsbuttom.RSButtonMetro btn_menu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nama;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
