/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
import Master.*;
import Transaksi.*;
import Koneksi.Koneksi;
import Koneksi.Session;
import java.awt.Color;

/**
 *
 * @author Lenovo
 */
public class Dashboard_Petugas extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */

    
    boolean[] stat = new boolean[10];

    Dokter dokter1 = new Dokter();
    Kamar kamar1 = new Kamar();
    Pasien pasien1 = new Pasien();
    Obat obat1 = new Obat();
    Petugas petugas1 = new Petugas();
    User user1 = new User();
    Tindakan tindakan1 = new Tindakan();
    RawatInap inap1 = new RawatInap();
    RawatJalan jalan1 = new RawatJalan();
    Riwayat riwayat1 = new Riwayat();
    public Dashboard_Petugas() {
        initComponents();
        addToPane();
        String akses1 = Session.getAkses();
        akses.setText(akses1);
        String nama1 = Session.getId();
        nama.setText(nama1);
        
    }
    private void resetstat() {
        for (int i = 0; i < 10; i++) {
            stat[i] = false;
        }
    }
    private void addToPane() {
        jDesktopPane1.add(dokter1);
        jDesktopPane1.add(kamar1);
        jDesktopPane1.add(pasien1);
        jDesktopPane1.add(obat1);
        jDesktopPane1.add(petugas1);
        jDesktopPane1.add(user1);
        jDesktopPane1.add(tindakan1);
        jDesktopPane1.add(inap1);
        jDesktopPane1.add(jalan1);
        jDesktopPane1.add(riwayat1);
    }
    private void hide_pane() {
        if (stat[0] == true) {
            dokter1.dispose();
        }
        if (stat[1] == true) {
            kamar1.dispose();
        }
        if (stat[2] == true) {
            pasien1.dispose();
        }
        if (stat[3] == true) {
            obat1.dispose();
        }
        if (stat[4] == true) {
            petugas1.dispose();
        }
        if (stat[5] = true) {
            user1.dispose();
        }
        if (stat[6] == true) {
            tindakan1.dispose();
        }
        if (stat[7] == true) {
            inap1.dispose();
        }
        if (stat[8] == true) {
            jalan1.dispose();
        }
        if (stat[9] == true) {
            riwayat1.dispose();
        }
        resetstat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_menu = new rsbuttom.RSButtonMetro();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        akses = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn2 = new rsbuttom.RSButtonMetro();
        btn6 = new rsbuttom.RSButtonMetro();
        btn5 = new rsbuttom.RSButtonMetro();
        btn4 = new rsbuttom.RSButtonMetro();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(1, 152, 117));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 60));
        jPanel2.setLayout(null);

        btn_menu.setBackground(new java.awt.Color(1, 152, 117));
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btn_menu.setColorHover(new java.awt.Color(1, 152, 117));
        btn_menu.setColorNormal(new java.awt.Color(1, 152, 117));
        btn_menu.setColorPressed(new java.awt.Color(1, 152, 117));
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn_menu);
        btn_menu.setBounds(19, 11, 59, 35);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Nama");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(1040, 10, 60, 17);

        nama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("jLabel6");
        jPanel2.add(nama);
        nama.setBounds(1130, 10, 120, 17);

        akses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akses.setForeground(new java.awt.Color(255, 255, 255));
        akses.setText("jLabel6");
        jPanel2.add(akses);
        akses.setBounds(1130, 30, 120, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Akses");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(1040, 30, 40, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(1350, 0, 20, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(1330, -10, 30, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1366, 60);

        pnlMenu.setBackground(new java.awt.Color(214, 217, 223));

        jPanel4.setBackground(new java.awt.Color(214, 217, 223));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Transaksi");

        btn2.setBackground(new java.awt.Color(214, 217, 223));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rawatJalan.png"))); // NOI18N
        btn2.setText("R. JALAN");
        btn2.setColorHover(new java.awt.Color(166, 166, 166));
        btn2.setColorNormal(new java.awt.Color(214, 217, 223));
        btn2.setColorPressed(new java.awt.Color(166, 166, 166));
        btn2.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn2.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn2.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn2.setIconTextGap(25);
        btn2.setPreferredSize(new java.awt.Dimension(180, 50));
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn2MousePressed(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(214, 217, 223));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rawatinap.png"))); // NOI18N
        btn6.setText("R. INAP");
        btn6.setColorHover(new java.awt.Color(166, 166, 166));
        btn6.setColorNormal(new java.awt.Color(214, 217, 223));
        btn6.setColorPressed(new java.awt.Color(166, 166, 166));
        btn6.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn6.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn6.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn6.setIconTextGap(25);
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn6MousePressed(evt);
            }
        });
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(214, 217, 223));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pasien.png"))); // NOI18N
        btn5.setText("PASIEN");
        btn5.setColorHover(new java.awt.Color(166, 166, 166));
        btn5.setColorNormal(new java.awt.Color(214, 217, 223));
        btn5.setColorPressed(new java.awt.Color(166, 166, 166));
        btn5.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn5.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn5.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn5.setIconTextGap(25);
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn5MousePressed(evt);
            }
        });
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(214, 217, 223));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/riwayat.png"))); // NOI18N
        btn4.setText("RIWAYAT");
        btn4.setColorHover(new java.awt.Color(166, 166, 166));
        btn4.setColorNormal(new java.awt.Color(214, 217, 223));
        btn4.setColorPressed(new java.awt.Color(166, 166, 166));
        btn4.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn4.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn4.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn4.setIconTextGap(25);
        btn4.setMargin(new java.awt.Insets(22, 14, 2, 14));
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn4MousePressed(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlMenu);
        pnlMenu.setBounds(0, 60, 180, 710);

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("BigNoodleTitling", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SELAMAT DATANG DI SISTEM INFORMASI");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(336, 74, 525, 54);

        jLabel8.setFont(new java.awt.Font("BigNoodleTitling", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JL. RAYA WONOREJO NO. 167, LUMAJANG");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(443, 186, 266, 27);

        jLabel9.setFont(new java.awt.Font("BigNoodleTitling", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KLINIK KESEHATAN HUSADA MULIA");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(408, 134, 342, 41);

        jLabel10.setFont(new java.awt.Font("BigNoodleTitling", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/hospital_icon-icons.com_76234.png"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(450, 300, 256, 290);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/free-dark-green-wallpaper-41165-42149-hd-wallpapers.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 1150, 670);

        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(200, 80, 1150, 670);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
//        new CambiaPanel(jPanel5,new RawatJalan());
        hide_pane();
        stat[8] = true;
        
        jalan1  = new RawatJalan();
        jDesktopPane1.add(jalan1);
        jalan1.setVisible(true);
        if(this.btn2.isSelected()){
            
            this.btn2.setColorNormal(new Color(166,166,166));
            this.btn2.setColorHover(new Color(166,166,166));
            this.btn2.setColorPressed(new Color(166,166,166));
            
            this.btn4.setColorNormal(new Color(214,217,223));
            this.btn4.setColorHover(new Color(166,166,166));
            this.btn4.setColorPressed(new Color(214,217,223));
            
            this.btn5.setColorNormal(new Color(214,217,223));
            this.btn5.setColorHover(new Color(166,166,166));
            this.btn5.setColorPressed(new Color(214,217,223));
            
            this.btn6.setColorNormal(new Color(214,217,223));
            this.btn6.setColorHover(new Color(166,166,166));
            this.btn6.setColorPressed(new Color(214,217,223));
            
        }
        else {
            this.btn2.setColorNormal(new Color(214,217,223));
            this.btn2.setColorHover(new Color(166,166,166));
            this.btn2.setColorPressed(new Color(214,217,223));       
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        int posisi = this.pnlMenu.getX();
        if (posisi > -1){
           Animacion.Animacion.mover_izquierda(0, -188, 3, 2, pnlMenu);
        } else {
           Animacion.Animacion.mover_derecha(-188, 0, 3, 2, pnlMenu);
        }
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        hide_pane();
        stat[2] = true;
        
        pasien1  = new Pasien();
        jDesktopPane1.add(pasien1);
        pasien1.setVisible(true);
        if(this.btn5.isSelected()){
            
            this.btn2.setColorNormal(new Color(214,217,223));
            this.btn2.setColorHover(new Color(166,166,166));
            this.btn2.setColorPressed(new Color(214,217,223));

            this.btn4.setColorNormal(new Color(214,217,223));
            this.btn4.setColorHover(new Color(166,166,166));
            this.btn4.setColorPressed(new Color(214,217,223));
            
            this.btn5.setColorNormal(new Color(166,166,166));
            this.btn5.setColorHover(new Color(166,166,166));
            this.btn5.setColorPressed(new Color(166,166,166));
            
            this.btn6.setColorNormal(new Color(214,217,223));
            this.btn6.setColorHover(new Color(166,166,166));
            this.btn6.setColorPressed(new Color(214,217,223));
            
        }
        else {
            this.btn5.setColorNormal(new Color(214,217,223));
            this.btn5.setColorHover(new Color(166,166,166));
            this.btn5.setColorPressed(new Color(214,217,223));       
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        hide_pane();
        stat[7] = true;
        
        inap1  = new RawatInap();
        jDesktopPane1.add(inap1);
        inap1.setVisible(true);
        if(this.btn6.isSelected()){
            
            this.btn2.setColorNormal(new Color(214,217,223));
            this.btn2.setColorHover(new Color(166,166,166));
            this.btn2.setColorPressed(new Color(214,217,223));
                     
            this.btn4.setColorNormal(new Color(214,217,223));
            this.btn4.setColorHover(new Color(166,166,166));
            this.btn4.setColorPressed(new Color(214,217,223));
            
            this.btn5.setColorNormal(new Color(214,217,223));
            this.btn5.setColorHover(new Color(166,166,166));
            this.btn5.setColorPressed(new Color(214,217,223));
            
            this.btn6.setColorNormal(new Color(166,166,166));
            this.btn6.setColorHover(new Color(166,166,166));
            this.btn6.setColorPressed(new Color(166,166,166));

        }
        else {
            this.btn6.setColorNormal(new Color(214,217,223));
            this.btn6.setColorHover(new Color(166,166,166));
            this.btn6.setColorPressed(new Color(214,217,223));       
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MousePressed
        // TODO add your handling code here:

        this.btn2.setSelected(true);
        this.btn4.setSelected(false);
        this.btn5.setSelected(false);
        this.btn6.setSelected(false);
       
    }//GEN-LAST:event_btn2MousePressed

    private void btn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MousePressed
        // TODO add your handling code here:
        this.btn2.setSelected(false);
        this.btn4.setSelected(true);
        this.btn5.setSelected(false);
        this.btn6.setSelected(false);
    }//GEN-LAST:event_btn4MousePressed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        hide_pane();
        stat[9] = true;
        
        riwayat1  = new Riwayat();
        jDesktopPane1.add(riwayat1);
        riwayat1.setVisible(true);
        if(this.btn4.isSelected()){

            this.btn2.setColorNormal(new Color(214,217,223));
            this.btn2.setColorHover(new Color(166,166,166));
            this.btn2.setColorPressed(new Color(214,217,223));

            this.btn4.setColorNormal(new Color(166,166,166));
            this.btn4.setColorHover(new Color(166,166,166));
            this.btn4.setColorPressed(new Color(166,166,166));

            this.btn5.setColorNormal(new Color(214,217,223));
            this.btn5.setColorHover(new Color(166,166,166));
            this.btn5.setColorPressed(new Color(214,217,223));

            this.btn6.setColorNormal(new Color(214,217,223));
            this.btn6.setColorHover(new Color(166,166,166));
            this.btn6.setColorPressed(new Color(214,217,223));
        }
        else {
            this.btn4.setColorNormal(new Color(214,217,223));
            this.btn4.setColorHover(new Color(166,166,166));
            this.btn4.setColorPressed(new Color(214,217,223));
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MousePressed
        // TODO add your handling code here:

        this.btn2.setSelected(false);
        this.btn4.setSelected(false);
        this.btn5.setSelected(true);
        this.btn6.setSelected(false);
    }//GEN-LAST:event_btn5MousePressed

    private void btn6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MousePressed
        // TODO add your handling code here:
        this.btn2.setSelected(false);
        this.btn4.setSelected(false);
        this.btn5.setSelected(false);
        this.btn6.setSelected(true);
    }//GEN-LAST:event_btn6MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame. ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akses;
    private rsbuttom.RSButtonMetro btn2;
    private rsbuttom.RSButtonMetro btn4;
    private rsbuttom.RSButtonMetro btn5;
    private rsbuttom.RSButtonMetro btn6;
    private rsbuttom.RSButtonMetro btn_menu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nama;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
